//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace RadioTimeOpmlApi.com.radiotime.opml {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RadioSoap", Namespace="http://www.sonos.com/Services/1.1")]
    public partial class Radio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private credentials credentialsValueField;
        
        private System.Threading.SendOrPostCallback getMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMediaMetadataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMediaURIOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getScrollIndicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSessionIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLastUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback reportStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Radio() {
            this.Url = global::RadioTimeOpmlApi.Properties.Settings.Default.RadioTimeOpmlApi_com_radiotime_opml_Radio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public credentials credentialsValue {
            get {
                return this.credentialsValueField;
            }
            set {
                this.credentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getMetadataCompletedEventHandler getMetadataCompleted;
        
        /// <remarks/>
        public event getMediaMetadataCompletedEventHandler getMediaMetadataCompleted;
        
        /// <remarks/>
        public event getMediaURICompletedEventHandler getMediaURICompleted;
        
        /// <remarks/>
        public event searchCompletedEventHandler searchCompleted;
        
        /// <remarks/>
        public event getScrollIndicesCompletedEventHandler getScrollIndicesCompleted;
        
        /// <remarks/>
        public event getSessionIdCompletedEventHandler getSessionIdCompleted;
        
        /// <remarks/>
        public event getLastUpdateCompletedEventHandler getLastUpdateCompleted;
        
        /// <remarks/>
        public event reportStatusCompletedEventHandler reportStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#getMetadata", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public metadataResponse getMetadata(string id, int index, int count, bool recursive) {
            object[] results = this.Invoke("getMetadata", new object[] {
                        id,
                        index,
                        count,
                        recursive});
            return ((metadataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMetadataAsync(string id, int index, int count, bool recursive) {
            this.getMetadataAsync(id, index, count, recursive, null);
        }
        
        /// <remarks/>
        public void getMetadataAsync(string id, int index, int count, bool recursive, object userState) {
            if ((this.getMetadataOperationCompleted == null)) {
                this.getMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetadataOperationCompleted);
            }
            this.InvokeAsync("getMetadata", new object[] {
                        id,
                        index,
                        count,
                        recursive}, this.getMetadataOperationCompleted, userState);
        }
        
        private void OngetMetadataOperationCompleted(object arg) {
            if ((this.getMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetadataCompleted(this, new getMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#getMediaMetadata", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public mediaMetadata getMediaMetadata(string id) {
            object[] results = this.Invoke("getMediaMetadata", new object[] {
                        id});
            return ((mediaMetadata)(results[0]));
        }
        
        /// <remarks/>
        public void getMediaMetadataAsync(string id) {
            this.getMediaMetadataAsync(id, null);
        }
        
        /// <remarks/>
        public void getMediaMetadataAsync(string id, object userState) {
            if ((this.getMediaMetadataOperationCompleted == null)) {
                this.getMediaMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMediaMetadataOperationCompleted);
            }
            this.InvokeAsync("getMediaMetadata", new object[] {
                        id}, this.getMediaMetadataOperationCompleted, userState);
        }
        
        private void OngetMediaMetadataOperationCompleted(object arg) {
            if ((this.getMediaMetadataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMediaMetadataCompleted(this, new getMediaMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#getMediaURI", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getMediaURI(string id) {
            object[] results = this.Invoke("getMediaURI", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMediaURIAsync(string id) {
            this.getMediaURIAsync(id, null);
        }
        
        /// <remarks/>
        public void getMediaURIAsync(string id, object userState) {
            if ((this.getMediaURIOperationCompleted == null)) {
                this.getMediaURIOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMediaURIOperationCompleted);
            }
            this.InvokeAsync("getMediaURI", new object[] {
                        id}, this.getMediaURIOperationCompleted, userState);
        }
        
        private void OngetMediaURIOperationCompleted(object arg) {
            if ((this.getMediaURICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMediaURICompleted(this, new getMediaURICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#search", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public metadataResponse search(string id, string term, int index, int count) {
            object[] results = this.Invoke("search", new object[] {
                        id,
                        term,
                        index,
                        count});
            return ((metadataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void searchAsync(string id, string term, int index, int count) {
            this.searchAsync(id, term, index, count, null);
        }
        
        /// <remarks/>
        public void searchAsync(string id, string term, int index, int count, object userState) {
            if ((this.searchOperationCompleted == null)) {
                this.searchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchOperationCompleted);
            }
            this.InvokeAsync("search", new object[] {
                        id,
                        term,
                        index,
                        count}, this.searchOperationCompleted, userState);
        }
        
        private void OnsearchOperationCompleted(object arg) {
            if ((this.searchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchCompleted(this, new searchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#getScrollIndices", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getScrollIndices(string id) {
            object[] results = this.Invoke("getScrollIndices", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getScrollIndicesAsync(string id) {
            this.getScrollIndicesAsync(id, null);
        }
        
        /// <remarks/>
        public void getScrollIndicesAsync(string id, object userState) {
            if ((this.getScrollIndicesOperationCompleted == null)) {
                this.getScrollIndicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetScrollIndicesOperationCompleted);
            }
            this.InvokeAsync("getScrollIndices", new object[] {
                        id}, this.getScrollIndicesOperationCompleted, userState);
        }
        
        private void OngetScrollIndicesOperationCompleted(object arg) {
            if ((this.getScrollIndicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getScrollIndicesCompleted(this, new getScrollIndicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#getSessionId", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSessionId() {
            object[] results = this.Invoke("getSessionId", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSessionIdAsync() {
            this.getSessionIdAsync(null);
        }
        
        /// <remarks/>
        public void getSessionIdAsync(object userState) {
            if ((this.getSessionIdOperationCompleted == null)) {
                this.getSessionIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSessionIdOperationCompleted);
            }
            this.InvokeAsync("getSessionId", new object[0], this.getSessionIdOperationCompleted, userState);
        }
        
        private void OngetSessionIdOperationCompleted(object arg) {
            if ((this.getSessionIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSessionIdCompleted(this, new getSessionIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#getLastUpdate", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetLastUpdateResponse getLastUpdate() {
            object[] results = this.Invoke("getLastUpdate", new object[0]);
            return ((GetLastUpdateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getLastUpdateAsync() {
            this.getLastUpdateAsync(null);
        }
        
        /// <remarks/>
        public void getLastUpdateAsync(object userState) {
            if ((this.getLastUpdateOperationCompleted == null)) {
                this.getLastUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLastUpdateOperationCompleted);
            }
            this.InvokeAsync("getLastUpdate", new object[0], this.getLastUpdateOperationCompleted, userState);
        }
        
        private void OngetLastUpdateOperationCompleted(object arg) {
            if ((this.getLastUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLastUpdateCompleted(this, new getLastUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("credentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sonos.com/Services/1.1#reportStatus", RequestNamespace="http://www.sonos.com/Services/1.1", ResponseNamespace="http://www.sonos.com/Services/1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reportStatus(string id, string code, string message, string url) {
            this.Invoke("reportStatus", new object[] {
                        id,
                        code,
                        message,
                        url});
        }
        
        /// <remarks/>
        public void reportStatusAsync(string id, string code, string message, string url) {
            this.reportStatusAsync(id, code, message, url, null);
        }
        
        /// <remarks/>
        public void reportStatusAsync(string id, string code, string message, string url, object userState) {
            if ((this.reportStatusOperationCompleted == null)) {
                this.reportStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreportStatusOperationCompleted);
            }
            this.InvokeAsync("reportStatus", new object[] {
                        id,
                        code,
                        message,
                        url}, this.reportStatusOperationCompleted, userState);
        }
        
        private void OnreportStatusOperationCompleted(object arg) {
            if ((this.reportStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reportStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sonos.com/Services/1.1", IsNullable=false)]
    public partial class credentials : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private string deviceIdField;
        
        private string deviceProviderField;
        
        private string sessionIdField;
        
        private string trackingField;
        
        private string directivesField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
            }
        }
        
        /// <remarks/>
        public string deviceProvider {
            get {
                return this.deviceProviderField;
            }
            set {
                this.deviceProviderField = value;
            }
        }
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public string tracking {
            get {
                return this.trackingField;
            }
            set {
                this.trackingField = value;
            }
        }
        
        /// <remarks/>
        public string directives {
            get {
                return this.directivesField;
            }
            set {
                this.directivesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    public partial class GetLastUpdateResponse {
        
        private string catalogField;
        
        private string favoritesField;
        
        private int pollIntervalField;
        
        /// <remarks/>
        public string catalog {
            get {
                return this.catalogField;
            }
            set {
                this.catalogField = value;
            }
        }
        
        /// <remarks/>
        public string favorites {
            get {
                return this.favoritesField;
            }
            set {
                this.favoritesField = value;
            }
        }
        
        /// <remarks/>
        public int pollInterval {
            get {
                return this.pollIntervalField;
            }
            set {
                this.pollIntervalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    public partial class mediaCollection {
        
        private string idField;
        
        private string titleField;
        
        private string itemTypeField;
        
        private bool authRequiredField;
        
        private bool canPlayField;
        
        private bool canEnumerateField;
        
        private bool canCacheField;
        
        private bool homogeneousField;
        
        private bool canAddToFavoriteField;
        
        private bool canScrollField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string itemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool authRequired {
            get {
                return this.authRequiredField;
            }
            set {
                this.authRequiredField = value;
            }
        }
        
        /// <remarks/>
        public bool canPlay {
            get {
                return this.canPlayField;
            }
            set {
                this.canPlayField = value;
            }
        }
        
        /// <remarks/>
        public bool canEnumerate {
            get {
                return this.canEnumerateField;
            }
            set {
                this.canEnumerateField = value;
            }
        }
        
        /// <remarks/>
        public bool canCache {
            get {
                return this.canCacheField;
            }
            set {
                this.canCacheField = value;
            }
        }
        
        /// <remarks/>
        public bool homogeneous {
            get {
                return this.homogeneousField;
            }
            set {
                this.homogeneousField = value;
            }
        }
        
        /// <remarks/>
        public bool canAddToFavorite {
            get {
                return this.canAddToFavoriteField;
            }
            set {
                this.canAddToFavoriteField = value;
            }
        }
        
        /// <remarks/>
        public bool canScroll {
            get {
                return this.canScrollField;
            }
            set {
                this.canScrollField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    public partial class scheduleMetadata {
        
        private string startTimeField;
        
        private string endTimeField;
        
        private int durationField;
        
        private string titleField;
        
        private string stationIdField;
        
        private string showIdField;
        
        private string logoField;
        
        private bool isRecurringField;
        
        private string recurDaysField;
        
        /// <remarks/>
        public string startTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public string endTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        public int duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string stationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
            }
        }
        
        /// <remarks/>
        public string showId {
            get {
                return this.showIdField;
            }
            set {
                this.showIdField = value;
            }
        }
        
        /// <remarks/>
        public string logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
            }
        }
        
        /// <remarks/>
        public bool isRecurring {
            get {
                return this.isRecurringField;
            }
            set {
                this.isRecurringField = value;
            }
        }
        
        /// <remarks/>
        public string recurDays {
            get {
                return this.recurDaysField;
            }
            set {
                this.recurDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    public partial class streamMetadata {
        
        private string currentShowIdField;
        
        private string currentShowField;
        
        private string currentHostField;
        
        private int bitrateField;
        
        private int reliabilityField;
        
        private string logoField;
        
        private string titleField;
        
        private string subtitleField;
        
        private int secondsRemainingField;
        
        private int secondsToNextShowField;
        
        private string nextShowStationIdField;
        
        private int nextShowSecondsField;
        
        /// <remarks/>
        public string currentShowId {
            get {
                return this.currentShowIdField;
            }
            set {
                this.currentShowIdField = value;
            }
        }
        
        /// <remarks/>
        public string currentShow {
            get {
                return this.currentShowField;
            }
            set {
                this.currentShowField = value;
            }
        }
        
        /// <remarks/>
        public string currentHost {
            get {
                return this.currentHostField;
            }
            set {
                this.currentHostField = value;
            }
        }
        
        /// <remarks/>
        public int bitrate {
            get {
                return this.bitrateField;
            }
            set {
                this.bitrateField = value;
            }
        }
        
        /// <remarks/>
        public int reliability {
            get {
                return this.reliabilityField;
            }
            set {
                this.reliabilityField = value;
            }
        }
        
        /// <remarks/>
        public string logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
        
        /// <remarks/>
        public int secondsRemaining {
            get {
                return this.secondsRemainingField;
            }
            set {
                this.secondsRemainingField = value;
            }
        }
        
        /// <remarks/>
        public int secondsToNextShow {
            get {
                return this.secondsToNextShowField;
            }
            set {
                this.secondsToNextShowField = value;
            }
        }
        
        /// <remarks/>
        public string nextShowStationId {
            get {
                return this.nextShowStationIdField;
            }
            set {
                this.nextShowStationIdField = value;
            }
        }
        
        /// <remarks/>
        public int nextShowSeconds {
            get {
                return this.nextShowSecondsField;
            }
            set {
                this.nextShowSecondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    public partial class trackMetadata {
        
        private string artistIdField;
        
        private string artistField;
        
        private string composerIdField;
        
        private string composerField;
        
        private string albumIdField;
        
        private string albumField;
        
        private string albumArtURIField;
        
        private string albumArtistIdField;
        
        private string albumArtistField;
        
        private string genreIdField;
        
        private string genreField;
        
        private int durationField;
        
        private string associatedShowField;
        
        private string associatedHostField;
        
        private string titleField;
        
        /// <remarks/>
        public string artistId {
            get {
                return this.artistIdField;
            }
            set {
                this.artistIdField = value;
            }
        }
        
        /// <remarks/>
        public string artist {
            get {
                return this.artistField;
            }
            set {
                this.artistField = value;
            }
        }
        
        /// <remarks/>
        public string composerId {
            get {
                return this.composerIdField;
            }
            set {
                this.composerIdField = value;
            }
        }
        
        /// <remarks/>
        public string composer {
            get {
                return this.composerField;
            }
            set {
                this.composerField = value;
            }
        }
        
        /// <remarks/>
        public string albumId {
            get {
                return this.albumIdField;
            }
            set {
                this.albumIdField = value;
            }
        }
        
        /// <remarks/>
        public string album {
            get {
                return this.albumField;
            }
            set {
                this.albumField = value;
            }
        }
        
        /// <remarks/>
        public string albumArtURI {
            get {
                return this.albumArtURIField;
            }
            set {
                this.albumArtURIField = value;
            }
        }
        
        /// <remarks/>
        public string albumArtistId {
            get {
                return this.albumArtistIdField;
            }
            set {
                this.albumArtistIdField = value;
            }
        }
        
        /// <remarks/>
        public string albumArtist {
            get {
                return this.albumArtistField;
            }
            set {
                this.albumArtistField = value;
            }
        }
        
        /// <remarks/>
        public string genreId {
            get {
                return this.genreIdField;
            }
            set {
                this.genreIdField = value;
            }
        }
        
        /// <remarks/>
        public string genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        public int duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string associatedShow {
            get {
                return this.associatedShowField;
            }
            set {
                this.associatedShowField = value;
            }
        }
        
        /// <remarks/>
        public string associatedHost {
            get {
                return this.associatedHostField;
            }
            set {
                this.associatedHostField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    public partial class mediaMetadata {
        
        private string idField;
        
        private string titleField;
        
        private string mimeTypeField;
        
        private string itemTypeField;
        
        private string languageField;
        
        private string countryField;
        
        private string genreIdField;
        
        private string genreField;
        
        private string twitterIdField;
        
        private bool liveNowField;
        
        private bool onDemandField;
        
        private trackMetadata trackMetadataField;
        
        private streamMetadata streamMetadataField;
        
        private scheduleMetadata scheduleMetadataField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        public string itemType {
            get {
                return this.itemTypeField;
            }
            set {
                this.itemTypeField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string genreId {
            get {
                return this.genreIdField;
            }
            set {
                this.genreIdField = value;
            }
        }
        
        /// <remarks/>
        public string genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        public string twitterId {
            get {
                return this.twitterIdField;
            }
            set {
                this.twitterIdField = value;
            }
        }
        
        /// <remarks/>
        public bool liveNow {
            get {
                return this.liveNowField;
            }
            set {
                this.liveNowField = value;
            }
        }
        
        /// <remarks/>
        public bool onDemand {
            get {
                return this.onDemandField;
            }
            set {
                this.onDemandField = value;
            }
        }
        
        /// <remarks/>
        public trackMetadata trackMetadata {
            get {
                return this.trackMetadataField;
            }
            set {
                this.trackMetadataField = value;
            }
        }
        
        /// <remarks/>
        public streamMetadata streamMetadata {
            get {
                return this.streamMetadataField;
            }
            set {
                this.streamMetadataField = value;
            }
        }
        
        /// <remarks/>
        public scheduleMetadata scheduleMetadata {
            get {
                return this.scheduleMetadataField;
            }
            set {
                this.scheduleMetadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sonos.com/Services/1.1")]
    public partial class metadataResponse {
        
        private int indexField;
        
        private int countField;
        
        private int totalField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public int index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public int total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mediaCollection", typeof(mediaCollection))]
        [System.Xml.Serialization.XmlElementAttribute("mediaMetadata", typeof(mediaMetadata))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getMetadataCompletedEventHandler(object sender, getMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public metadataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((metadataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getMediaMetadataCompletedEventHandler(object sender, getMediaMetadataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMediaMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMediaMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mediaMetadata Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mediaMetadata)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getMediaURICompletedEventHandler(object sender, getMediaURICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMediaURICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMediaURICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void searchCompletedEventHandler(object sender, searchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public metadataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((metadataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getScrollIndicesCompletedEventHandler(object sender, getScrollIndicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getScrollIndicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getScrollIndicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getSessionIdCompletedEventHandler(object sender, getSessionIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSessionIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSessionIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getLastUpdateCompletedEventHandler(object sender, getLastUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLastUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLastUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetLastUpdateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetLastUpdateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void reportStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591